
name: runDatagen
on:
    workflow_dispatch:
          inputs:
              patch:
                  description: Run dataGen to go
                  required: true
    pull_request:
    push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLISH_SUFFIX: snapshots
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      PATCH_NUMBER: ${{ github.event.inputs.patch }}
      PUBLISHING: ${{ github.event.inputs.publish }}
    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          
      - name: dataGen
        run: ./gradlew runDatagen

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.ref.outputs.branch }}
          path: build/libs/
